routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['as' => 'index','uses' => 'IndexController@index']);


Route::post('login', ['as' => 'login','uses' => 'Auth\LoginController@login']);
Route::get('logout', ['as' => 'logout','uses' => 'Auth\LoginController@logout']);

Route::get('password/remind', ['as'=>'password.remind','uses'=>'Auth\ForgotPasswordController@showLinkRequestForm']);
Route::post('password/remind', ['as'=>'send.password.remind','uses'=>'Auth\ForgotPasswordController@sendResetLinkEmail']);
Route::get('password/reset/{token}', ['as'=>'password.reset', 'uses'=>'Auth\ResetPasswordController@showResetForm']);
Route::post('password/reset', ['as'=>'password.update','uses'=>'Auth\ResetPasswordController@reset']);


Route::group(['middleware' => ['auth'],'prefix' => 'home', 'as' => 'home.'], function() {
    Route::get('/', ['as' => 'index','uses' => 'Dashboard\DashboardController@index']);

    Route::get('profile', ['as' => 'profile','uses' => 'Dashboard\ProfileController@index']);
    Route::post('profile/details/update', ['as' => 'profile.update.details','uses' => 'Dashboard\ProfileController@updateDetails']);
    Route::post('profile/login-details/update', ['as' => 'profile.update.login-details','uses' => 'Dashboard\ProfileController@updateLoginDetails']);

    Route::get('user', ['as' => 'user.list','uses' => 'Dashboard\UsersController@index']);
    Route::get('user/create', ['as' => 'user.create','uses' => 'Dashboard\UsersController@create']);
    Route::post('user/create', ['as' => 'user.store','uses' => 'Dashboard\UsersController@store']);
    Route::get('user/{user_id}/edit', ['as' => 'user.edit','uses' => 'Dashboard\UsersController@edit']);
    Route::post('user/{user_id}/update/details', ['as' => 'user.update.details','uses' => 'Dashboard\UsersController@updateDetails']);
    Route::post('user/{user_id}/update/login-details', ['as' => 'user.update.login-details','uses' => 'Dashboard\UsersController@updateLoginDetails']);      //----------testar
    Route::delete('user/{user_id}/delete', ['as' => 'user.delete','uses' => 'Dashboard\UsersController@destroy']);

    Route::get('category', ['as' => 'category.index','uses' => 'Dashboard\CategoriesController@index']);
    Route::get('category/create', ['as' => 'category.create','uses' => 'Dashboard\CategoriesController@create']);
    Route::post('category/create', ['as' => 'category.store','uses' => 'Dashboard\CategoriesController@store']);
    Route::get('category/{user_id}/edit', ['as' => 'category.edit','uses' => 'Dashboard\CategoriesController@edit']);
    Route::post('category/{user_id}/update', ['as' => 'category.update','uses' => 'Dashboard\CategoriesController@update']);
    Route::delete('category/{user_id}/delete', ['as' => 'category.delete','uses' => 'Dashboard\CategoriesController@destroy']);

    Route::get('link', ['as' => 'link.index','uses' => 'Dashboard\LinksController@index']);
    Route::get('link/create', ['as' => 'link.create','uses' => 'Dashboard\LinksController@create']);
    Route::post('link/create', ['as' => 'link.store','uses' => 'Dashboard\LinksController@store']);
    Route::get('link/{user_id}/edit', ['as' => 'link.edit','uses' => 'Dashboard\LinksController@edit']);
    Route::post('link/{user_id}/update', ['as' => 'link.update','uses' => 'Dashboard\LinksController@update']);
    Route::delete('link/{user_id}/delete', ['as' => 'link.delete','uses' => 'Dashboard\LinksController@destroy']);
});

Route::get('/{code}', ['as' => 'url.redirect','uses' => 'IndexController@urlredirect']);

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'slug'
    ];

    public function links()
    {
        return $this->hasMany('App\Models\link','category_id');
    }
}

app/Http/Controllers/Dashboard/CategoriesController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Requests\CreateCategoryRequest;
use App\Http\Requests\UpdateCategoryRequest;
use App\Models\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Str;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $peer_page = 15;
        $search = Input::get('search');

        $categories = Category::Query();
        if ($search <> "") {
            $categories->where(function ($q) use ($search) {
                $q->where('name', "like", "%{$search}%");
            });
        }
        $categories = $categories->paginate($peer_page);

        if ($search) {
            $categories->appends(['search' => $search]);
        }

        return view('dashboard.category.list', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.category.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCategoryRequest $request)
    {
        $category = new Category();
        $category->name = $request->name;
        $category->slug = $slug = Str::slug($request->name, '-');
        $category->save();

        return redirect()->route('home.category.index')->withSuccess('Categoria criada com sucesso!');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $edit = true;
        $category = Category::find($id);

        return view('dashboard.category.edit',compact('edit', 'category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCategoryRequest $request, $id)
    {
        $category = Category::find($id);
        $category->name = $request->name;
        $category->slug = $slug = Str::slug($request->name, '-');
        $category->save();
        return redirect()->back()->withSuccess('Categoria atualizada com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);
        $category->delete();

        return redirect()->route('home.category.index')->withSuccess('Categoria excluida com sucesso!');
    }
}

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\Category;
use App\Models\Link;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class DashboardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        $categories = Category::all();
        if(Auth::User()->type==2){
            $links = Link::where('client_id','=',Auth::User()->id)->get();
        }else{
            $links = Link::all();
        }


        return view('dashboard.admin', compact('users','categories','links'));
    }

}

app/Http/Controllers/Dashboard/LinksController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Requests\CreateLinkRequest;
use App\Http\Requests\UpdateLinkRequest;
use App\Models\Category;
use App\Models\Link;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Str;

class LinksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $peer_page = 15;
        $search = Input::get('search');
        $order = Input::get('order');

        $links = Link::Query();
        if(Auth::User()->type==2){
            $links->where('client_id','=',Auth::User()->id);
        }
        if ($search <> "") {
            $links->where(function ($q) use ($search) {
                $q->where('long_url', "like", "%{$search}%");
                $q->orwhere('name', "like", "%{$search}%");
            });
        }
        if($order <> ""){
            if($order==1){
                $links->orderBy('clicks','desc');
            }elseif($order==2){
                $links->orderBy('clicks','asc');
            }elseif($order==3){
                $links->orderBy('created_at','desc');
            }elseif($order==4){
                $links->orderBy('created_at','asc');
            }
        }else{
            $links->orderBy('created_at','desc');
        }
        $links = $links->paginate($peer_page);

        if ($search) {
            $links->appends(['search' => $search]);
        }

        return view('dashboard.link.list', compact('links'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::All();
        $clients = User::where('type','=',2)->get();
        return view('dashboard.link.add', compact('categories','clients'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateLinkRequest $request)
    {
        $hash = Str::random(8);
        $aux = Link::where('short_url','=',$hash)->get();
        while($aux->count()>0){
            $hash = Str::random(8);
            $aux = Link::where('short_url','=',$hash)->get();
        }


        $link = new Link();
        $link->long_url = $request->long_url;
        $link->short_url = $hash;
        $link->user_id = Auth::User()->id;
        $link->category_id = $request->category_id;
        $link->client_id = $request->client_id;
        $link->name = $request->name;
        $link->save();

        return redirect()->route('home.link.index')->withSuccess('Link criado com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $edit = true;
        $link = Link::find($id);
        $categories = Category::All();
        $clients = User::where('type','=',2)->get();
        return view('dashboard.link.edit',compact('edit', 'link','categories','clients'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateLinkRequest $request, $id)
    {
        $link = Link::find($id);
        $link->long_url = $request->long_url;
        $link->category_id = $request->category_id;
        $link->client_id = $request->client_id;
        $link->name = $request->name;
        $link->save();
        return redirect()->back()->withSuccess('Link atualizado com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $link = Link::find($id);
        $link->delete();

        return redirect()->route('home.link.index')->withSuccess('Link excluido com sucesso!');
    }
}

app/Http/Controllers/Dashboard/ProfileController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Requests\UpdateProfileDetailsRequest;
use App\Http\Requests\UpdateProfileLoginDetailsRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class ProfileController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $edit = true;
        $user = Auth::User();

        return view('dashboard.user.profile',compact('edit','user'));
    }

    /**
     * Update informações do usuario.
     *
     * @return \Illuminate\Http\Response
     */
    public function updateDetails(UpdateProfileDetailsRequest $request)
    {

        $user = Auth::User();
        $user->name = $request->name;
        $user->email = $request->email;
        $user->save();

        return redirect()->back()->withSuccess('Perfil atualizado com sucesso!');
    }

    /**
     * Update informações de login.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function updateLoginDetails(UpdateProfileLoginDetailsRequest $request)
    {
        $user = Auth::User();
        $user->password = $request->password;
        $user->save();

        return redirect()->back()->withSuccess('Perfil atualizado com sucesso!');
    }

}

resources/views/dashboard/category/add.blade.php
@extends('dashboard.layouts.master')

@section('content_header')
    <h1>
        Criar nova categoria
        <small>Detalhes da categoria</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('home.index') }}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li>Categorias</li>
        <li class="active">Criar</li>
      </ol>
@endsection

@section('content')

@include('partials.messages')
@if(Auth::User()->type==1)
    <form action="{{route('home.category.store')}}" method="POST">
    @csrf
        <div class="row">
            <div class="col-md-8">
                @include('dashboard.category.partials.details', ['edit' => false])
            </div>
        </div>

        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <button type="submit" class="btn btn-primary">
                    <i class="fa fa-save"></i>
                    Criar categoria
                </button>
            </div>
        </div>
    </form>
@endif
@stop

resources/views/dashboard/category/edit.blade.php
@extends('dashboard.layouts.master')

@section('content_header')
    <h1>
        {{ $category->name }}
        <small>editar detalhes da categoria</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('home.index') }}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li>Categorias</li>
        <li class="active">Editar</li>
      </ol>
@endsection

@section('content')

@include('partials.messages')

<div class="nav-tabs-custom">
    <!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active">
        <a href="#details" aria-controls="details" role="tab" data-toggle="tab">
            <i class="glyphicon glyphicon-th"></i>
            Detalhes
        </a>
    </li>
</ul>
<!-- Tab panes -->
<div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="details">
        <div class="row">
            <div class="col-lg-8 col-md-7">
                @if(Auth::User()->type==1)
                    <form action="{{route('home.category.update',$category->id)}}" method="post">
                    @csrf
                    @include('dashboard.category.partials.details')
                    </form>
                @endif
            </div>
        </div>
    </div>
</div>
</div>

@stop

resources/views/dashboard/category/list.blade.php
@extends('dashboard.layouts.master')

@section('css')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/css/bootstrap-select.min.css">
@endsection

@section('content_header')
<h1>
    Categorias
</h1>
<ol class="breadcrumb">
    <li><a href="{{ route('home.index') }}"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Categorias</li>
</ol>
@endsection
@section('content')
@include('partials.messages')

<div class="row tab-search">
    <div class="col-md-2 col-xs-2">
        @if(Auth::User()->type==1)
        <a href="{{ route('home.category.create') }}" class="btn btn-success" id="add-user">
            <i class="glyphicon glyphicon-plus"></i>
            Adicionar categoria
        </a>
        @endif
    </div>
    <div class="col-md-5 col-xs-3">

    </div>

    <form method="GET" action="" accept-charset="UTF-8" id="category-form">
        <div class="col-md-2 col-xs-3">

        </div>
        <div class="col-md-3 col-xs-4">
            <div class="input-group custom-search-form">
                <input type="text" class="form-control" name="search" value="{{ app('request')->input('search') }}" placeholder="Procure por categorias...">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit" id="search-users-btn">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                    @if (app('request')->input('search') != '')
                        <a href="{{ route('home.category.index') }}" class="btn btn-danger" type="button" >
                            <span class="glyphicon glyphicon-remove"></span>
                        </a>
                    @endif
                </span>
            </div>
        </div>
    </form>

</div>

<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Lista de categorias cadastradas</h3>
            </div>
            <div class="box-body table-responsive no-padding">
                <div id="users-table-wrapper">
                    <table class="table table-hover table-striped">
                        <tbody>
                            <tr>
                                <th>Nome</th>
                                <th class="text-center">Ações</th>
                            </tr>
                            @if (count($categories))
                            @foreach ($categories as $category)
                            <tr>
                                <td>{{ $category->name }}</td>
                                <td class="text-center">
                                    @if(Auth::User()->type==1)
                                    <a href="{{ route('home.category.edit', $category->id) }}" class="btn btn-primary btn-circle edit" title="Editar categoria"
                                        data-toggle="tooltip" data-placement="top">
                                        <i class="glyphicon glyphicon-edit"></i>
                                    </a>
                                    @endif
                                    @if(Auth::User()->type==1)
                                    <a href="{{ route('home.category.delete', $category->id) }}" class="btn btn-danger btn-circle" title="Excluir categoria"
                                        data-toggle="tooltip"
                                        data-placement="top"
                                        data-method="DELETE"
                                        data-confirm-title="Por favor confirme"
                                        data-confirm-text="Tem certeza que deseja excluir essa categoria?"
                                        data-confirm-delete="Sim">
                                        <i class="glyphicon glyphicon-trash"></i>
                                    </a>
                                    @endif
                                </td>
                            </tr>
                            @endforeach
                            @else
                            <tr>
                                <td colspan="6"><em>Categorias não encontradas</em></td>
                            </tr>
                            @endif
                        </tbody>
                    </table>
                    {{ $categories->links() }}
                </div>
            </div>
        </div>
    </div>
</div>
@stop

@section('js')
    <script src="{{ asset('assets/delete.handler.js') }}"></script>
@stop