routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['as' => 'index','uses' => 'IndexController@index']);


Route::post('login', ['as' => 'login','uses' => 'Auth\LoginController@login']);
Route::get('logout', ['as' => 'logout','uses' => 'Auth\LoginController@logout']);

Route::get('password/remind', ['as'=>'password.remind','uses'=>'Auth\ForgotPasswordController@showLinkRequestForm']);
Route::post('password/remind', ['as'=>'send.password.remind','uses'=>'Auth\ForgotPasswordController@sendResetLinkEmail']);
Route::get('password/reset/{token}', ['as'=>'password.reset', 'uses'=>'Auth\ResetPasswordController@showResetForm']);
Route::post('password/reset', ['as'=>'password.update','uses'=>'Auth\ResetPasswordController@reset']);


Route::group(['middleware' => ['auth'],'prefix' => 'home', 'as' => 'home.'], function() {
    Route::get('/', ['as' => 'index','uses' => 'Dashboard\DashboardController@index']);

    Route::get('profile', ['as' => 'profile','uses' => 'Dashboard\ProfileController@index']);
    Route::post('profile/details/update', ['as' => 'profile.update.details','uses' => 'Dashboard\ProfileController@updateDetails']);
    Route::post('profile/login-details/update', ['as' => 'profile.update.login-details','uses' => 'Dashboard\ProfileController@updateLoginDetails']);

    Route::get('user', ['as' => 'user.list','uses' => 'Dashboard\UsersController@index']);
    Route::get('user/create', ['as' => 'user.create','uses' => 'Dashboard\UsersController@create']);
    Route::post('user/create', ['as' => 'user.store','uses' => 'Dashboard\UsersController@store']);
    Route::get('user/{user_id}/edit', ['as' => 'user.edit','uses' => 'Dashboard\UsersController@edit']);
    Route::post('user/{user_id}/update/details', ['as' => 'user.update.details','uses' => 'Dashboard\UsersController@updateDetails']);
    Route::post('user/{user_id}/update/login-details', ['as' => 'user.update.login-details','uses' => 'Dashboard\UsersController@updateLoginDetails']);      //----------testar
    Route::delete('user/{user_id}/delete', ['as' => 'user.delete','uses' => 'Dashboard\UsersController@destroy']);

    Route::get('category', ['as' => 'category.index','uses' => 'Dashboard\CategoriesController@index']);
    Route::get('category/create', ['as' => 'category.create','uses' => 'Dashboard\CategoriesController@create']);
    Route::post('category/create', ['as' => 'category.store','uses' => 'Dashboard\CategoriesController@store']);
    Route::get('category/{user_id}/edit', ['as' => 'category.edit','uses' => 'Dashboard\CategoriesController@edit']);
    Route::post('category/{user_id}/update', ['as' => 'category.update','uses' => 'Dashboard\CategoriesController@update']);
    Route::delete('category/{user_id}/delete', ['as' => 'category.delete','uses' => 'Dashboard\CategoriesController@destroy']);

    Route::get('link', ['as' => 'link.index','uses' => 'Dashboard\LinksController@index']);
    Route::get('link/create', ['as' => 'link.create','uses' => 'Dashboard\LinksController@create']);
    Route::post('link/create', ['as' => 'link.store','uses' => 'Dashboard\LinksController@store']);
    Route::get('link/{user_id}/edit', ['as' => 'link.edit','uses' => 'Dashboard\LinksController@edit']);
    Route::post('link/{user_id}/update', ['as' => 'link.update','uses' => 'Dashboard\LinksController@update']);
    Route::delete('link/{user_id}/delete', ['as' => 'link.delete','uses' => 'Dashboard\LinksController@destroy']);
});

Route::get('/{code}', ['as' => 'url.redirect','uses' => 'IndexController@urlredirect']);

app/Http/Controllers/Dashboard/CategoriesController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Requests\CreateCategoryRequest;
use App\Http\Requests\UpdateCategoryRequest;
use App\Models\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Str;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $peer_page = 15;
        $search = Input::get('search');

        $categories = Category::Query();
        if ($search <> "") {
            $categories->where(function ($q) use ($search) {
                $q->where('name', "like", "%{$search}%");
            });
        }
        $categories = $categories->paginate($peer_page);

        if ($search) {
            $categories->appends(['search' => $search]);
        }

        return view('dashboard.category.list', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.category.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCategoryRequest $request)
    {
        $category = new Category();
        $category->name = $request->name;
        $category->slug = $slug = Str::slug($request->name, '-');
        $category->save();

        return redirect()->route('home.category.index')->withSuccess('Categoria criada com sucesso!');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $edit = true;
        $category = Category::find($id);

        return view('dashboard.category.edit',compact('edit', 'category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCategoryRequest $request, $id)
    {
        $category = Category::find($id);
        $category->name = $request->name;
        $category->slug = $slug = Str::slug($request->name, '-');
        $category->save();
        return redirect()->back()->withSuccess('Categoria atualizada com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);
        $category->delete();

        return redirect()->route('home.category.index')->withSuccess('Categoria excluida com sucesso!');
    }
}

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\Category;
use App\Models\Link;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class DashboardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        $categories = Category::all();
        if(Auth::User()->type==2){
            $links = Link::where('client_id','=',Auth::User()->id)->get();
        }else{
            $links = Link::all();
        }


        return view('dashboard.admin', compact('users','categories','links'));
    }

}

app/Http/Controllers/Dashboard/LinksController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Requests\CreateLinkRequest;
use App\Http\Requests\UpdateLinkRequest;
use App\Models\Category;
use App\Models\Link;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Str;

class LinksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $peer_page = 15;
        $search = Input::get('search');
        $order = Input::get('order');

        $links = Link::Query();
        if(Auth::User()->type==2){
            $links->where('client_id','=',Auth::User()->id);
        }
        if ($search <> "") {
            $links->where(function ($q) use ($search) {
                $q->where('long_url', "like", "%{$search}%");
                $q->orwhere('name', "like", "%{$search}%");
            });
        }
        if($order <> ""){
            if($order==1){
                $links->orderBy('clicks','desc');
            }elseif($order==2){
                $links->orderBy('clicks','asc');
            }elseif($order==3){
                $links->orderBy('created_at','desc');
            }elseif($order==4){
                $links->orderBy('created_at','asc');
            }
        }else{
            $links->orderBy('created_at','desc');
        }
        $links = $links->paginate($peer_page);

        if ($search) {
            $links->appends(['search' => $search]);
        }

        return view('dashboard.link.list', compact('links'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::All();
        $clients = User::where('type','=',2)->get();
        return view('dashboard.link.add', compact('categories','clients'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateLinkRequest $request)
    {
        $hash = Str::random(8);
        $aux = Link::where('short_url','=',$hash)->get();
        while($aux->count()>0){
            $hash = Str::random(8);
            $aux = Link::where('short_url','=',$hash)->get();
        }


        $link = new Link();
        $link->long_url = $request->long_url;
        $link->short_url = $hash;
        $link->user_id = Auth::User()->id;
        $link->category_id = $request->category_id;
        $link->client_id = $request->client_id;
        $link->name = $request->name;
        $link->save();

        return redirect()->route('home.link.index')->withSuccess('Link criado com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $edit = true;
        $link = Link::find($id);
        $categories = Category::All();
        $clients = User::where('type','=',2)->get();
        return view('dashboard.link.edit',compact('edit', 'link','categories','clients'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateLinkRequest $request, $id)
    {
        $link = Link::find($id);
        $link->long_url = $request->long_url;
        $link->category_id = $request->category_id;
        $link->client_id = $request->client_id;
        $link->name = $request->name;
        $link->save();
        return redirect()->back()->withSuccess('Link atualizado com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $link = Link::find($id);
        $link->delete();

        return redirect()->route('home.link.index')->withSuccess('Link excluido com sucesso!');
    }
}

app/Http/Controllers/Dashboard/ProfileController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Requests\UpdateProfileDetailsRequest;
use App\Http\Requests\UpdateProfileLoginDetailsRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class ProfileController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $edit = true;
        $user = Auth::User();

        return view('dashboard.user.profile',compact('edit','user'));
    }

    /**
     * Update informações do usuario.
     *
     * @return \Illuminate\Http\Response
     */
    public function updateDetails(UpdateProfileDetailsRequest $request)
    {

        $user = Auth::User();
        $user->name = $request->name;
        $user->email = $request->email;
        $user->save();

        return redirect()->back()->withSuccess('Perfil atualizado com sucesso!');
    }

    /**
     * Update informações de login.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function updateLoginDetails(UpdateProfileLoginDetailsRequest $request)
    {
        $user = Auth::User();
        $user->password = $request->password;
        $user->save();

        return redirect()->back()->withSuccess('Perfil atualizado com sucesso!');
    }

}

resources/views/dashboard/includes/header.blade.php
<!-- Main Header -->
<header class="main-header">

    <!-- Logo -->
    <a href="{{ route('home.index') }}" class="logo">
        <span class="logo-lg">Encurtador</span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle</span>
        </a>
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                @if(Auth::check())
                <!-- User Account Menu -->
                <li class="dropdown user user-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <!-- hidden-xs hides the username on small devices so only the image appears. -->
                        <span class="hidden-xs">{{ Auth::User()->name }}</span>
                    </a>

                    <ul class="dropdown-menu">
                        <!-- Menu Body -->
                        <li class="user-body">
                            <a href="{{ route('home.profile') }}" class="btn btn-default btn-block">
                               <i class="fa fa-user"></i>
                               Meu Perfil
                            </a>


                            <a href="{{ route('logout') }}" class="btn btn-default btn-block">
                               <i class="fa fa-sign-out"></i>
                               Sair
                            </a>
                        </li>
                    </ul>
                </li>
                @endif
            </ul>
        </div>
    </nav>
</header>

resources/views/dashboard/includes/sidebar.blade.php
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="" class="img-circle" alt="User Image" />
            </div>
            <div class="pull-left info">
                <p>{{ Auth::user()->name }}</p>
                <!-- Status -->
                @can(Auth::check())
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                @endcan
            </div>
        </div>

        <!-- Sidebar Menu -->
        <ul class="sidebar-menu">
            <li class="">
                <a href="{{ route('home.index') }}">
                    <i class="fa fa-dashboard fa-fw"></i> <span>Home</span>
                </a>
            </li>
            @if(Auth::User()->type==1)
            <li class="">
                <a href="{{ route('home.user.list') }}">
                    <i class="fa fa-users fa-fw"></i> <span>Usuários</span>
                </a>
            </li>
            @endif
            @if(Auth::User()->type==1)
            <li class="">
                <a href="{{ route('home.category.index') }}">
                    <i class="fa fa-tags fa-fw"></i> <span>Categorias</span>
                </a>
            </li>
            @endif
            <li class="">
                <a href="{{ route('home.link.index') }}">
                    <i class="fa fa-link fw"></i> <span>Links</span>
                </a>
            </li>

        </ul><!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>